preprocess:
   input_data: data/raw/data.csv
   output_data: data/processed/data.csv

train:
   data: data/raw/data.csv
   model_path: models/model.pkl
   random_state: 42
   n_estimators: 100
   max_depth: 5 
 